config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get '/search' => 'search#index'

  devise_for :users

  as :user do
    get 'users', :to => 'venues#index', :as => :user_root
  end

  resources :users
  resources :venues do
    resources :reviews
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  namespace :api do
    resources :venues do
      resources :reviews, only: [:update]
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query]
      page_count = params[:page]
      @venues = Venue.venue_search(params[:query]).page(page_count).per(10)
      @reviews = Review.review_search(params[:query]).page(page_count).per(10)
      @users = User.search_by_username(params[:query])
      @users.each do |user|
        @venues << user.venues
        @venues = @venues.flatten
        @reviews << user.reviews
        @reviews = @reviews.flatten
      end
    end
  end
end

app/views/search/index.html.erb
<div class="full-height bg-img">
  <div class="row">
    <div class="small-12 medium-10 medium-centered large-8 large-centered columns show-footer">
      <% if @venues %>
        <% unless @venues.empty? %>
          <h1>Venue Results</h1>
          <div class="row">
            <div class="floating-container">
              <%= render @venues %>
            </div>
          </div>
        <% end %>
      <% end %>

      <% if @reviews %>
        <% unless @reviews.empty? %>
          <h1>Review Results</h1>
          <div class="row">
            <div class="floating-container">
              <% @reviews.each do |review| %>
                <p><%= link_to review.review_body, venue_path(review.venue) %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

      <%if @venues && @reviews %>
        <%if @venues.empty? && @reviews.empty? %>
          <h1>No Results Found</h1>
        <% end %>
      <% end %>
    </div>
  </div>
</div>