config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get '/search' => 'search#index'

  devise_for :users

  as :user do
    get 'users', :to => 'venues#index', :as => :user_root
  end

  resources :users
  resources :venues do
    resources :reviews
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  namespace :api do
    resources :venues do
      resources :reviews, only: [:update]
    end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base

  STATES = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL",
            "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA",
            "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE",
            "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK",
            "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT",
            "VA", "WA", "WV", "WI", "WY"]

  validates :venue_name, presence: true
  validates :street_name, presence: true
  validates :state, presence: true, inclusion: { in: STATES }
  validates :zip_code, presence: true, length: { is: 5 }
  validates :zip_code, numericality: { only_integer: true }
  validates :city, presence: true
  validates :user, presence: true

  has_many :reviews
  belongs_to :user

  include PgSearch
  pg_search_scope :venue_search,
                  against: [:venue_name,
                            :street_name,
                            :state,
                            :zip_code,
                            :city,
                            :description],
                  using: { tsearch: { prefix: true } }

  def deletable_by(user)
    return false if user.nil?
    user.admin? || self.user == user
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @venues = Venue.page(params[:page]).per(6)
  end

  def show
    @venue = Venue.find(params[:id])
    @reviews = @venue.reviews.page(params[:page]).per(6)
    @vote = Vote.new
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      flash.notice = "Venue added successfully"
      redirect_to venues_path
    else
      flash.notice = @venue.errors.full_messages.join(". ")
      render "new"
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    @venue.update(venue_params)
    if @venue.save
      flash.notice = "Venue added successfully"
      redirect_to venue_path(@venue)
    else
      flash.notice = @venue.errors.full_messages.join(". ")
      render "edit"
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy
    redirect_to venues_path
  end

  def welcome
    render "home", layout: false
  end

  private

  def venue_params
    params.require(:venue).permit(
      :venue_name,
      :street_name,
      :state,
      :zip_code,
      :city,
      :description,
      :price_range
    )
  end
end

app/views/venues/_reviews.html.erb
<% @reviews.each do |review| %>
<div class="row">
  <div id="review-<%= review.id %>">
    <li><%= review.review_body %></li>
    <% review.rating.times do %>
    &#127775
    <% end %>
    <div class="vote-wrap">
      <div class="upvote box">
        <%= button_to "helpful", "/api/venues/#{@venue.id}/reviews/#{review.id}", method:"patch", params: {up: "true", load_javascript: "false"} %>
      </div>
      <div class="helpful box"><%= review.revup_count %></div>
      <div class="downvote box">
        <%= button_to "not helpful", "/api/venues/#{@venue.id}/reviews/#{review.id}", method:"patch", params: {down: "true", load_javascript: "false"}%>
      </div>
      <div class="not-helpful box"><%= review.revdown_count %></div>
    </div>

    <% if review.deletable_by(current_user) %>
      <%= button_to "Delete Review", venue_review_path(@venue, review), class: "button", method: "delete", label: "Delete Review" %>
    <% end %>
    <% if review.deletable_by(current_user) %>
      <%= button_to "Edit Review", edit_venue_review_path(@venue, review), class: "button", method: "get", label: "Edit Review" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/venues/_venue.html.erb
<div class="large-4 medium-6 small-12 columns">
  <div class="image-wrapper overlay-fade-in animated fadeInLeft">
    <img src="http://www.skydiveseb.com/data6/images/9.08beachjumpfx5.jpg">

    <div class="panel">
      <p class="subheader"><%= venue.description %></p>
      <div class="image-overlay-content">
        <h4><%= link_to venue.venue_name, venue_path(venue) %></h4>
      </div>
    </div>
  </div>
</div>

app/views/venues/edit.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered large-8 large-centered columns">
    <h1>Update Venue</h1>

    <%= form_for(@venue) do |f| %>
    <div class="field">
      <%= f.label :venue_name, "Venue Name" %><br />
      <%= f.text_field :venue_name %>
    </div>

    <div class="field">
      <%= f.label :street_name, "Street Address" %><br />
      <%= f.text_field :street_name %>
    </div>

    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_field :city %>
    </div>

    <div class="field">
      <%= f.label :state %><br />
      <%= f.text_field :state %>
    </div>

    <div class="field">
      <%= f.label :zip_code, "Zip Code" %><br />
      <%= f.text_field :zip_code %>
    </div>

    <div class="field">
      <%= f.label :price_range, "Price Range" %><br />
      <%= f.text_field :price_range %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>

    <div class="actions">
      <%= f.submit "Submit Changes" %>
    </div>
    <% end %>
  </div>
</div>

app/views/venues/index.html.erb
<div class="show-footer bg-img">
  <div class="floating-container">
    <div class="row title-header">
      <h1 class="animated fadeInDown">Venues</h1>
    </div>
  </div>
    <%= render @venues %>
  <div class="venue-options">
    <hr>
    <div class="text-center">
      <a href="<%= new_venue_path %>" class="button">Add a New Venue!</a>
    </div>
    <div class="text-center">
      <a href="<%= venues_path %>" class="button">All Venues</a>
    </div>
    <div class="paginate-center">
      <%= paginate @venues %>
    </div>
  </div>
</div>

app/views/venues/new.html.erb
<div class="column">
  <div class="show-footer small-12 medium-10 medium-centered large-8 large-centered columns">
    <h1>New Venue Form</h1>

    <%= form_for(@venue) do |f| %>
    <div class="field">
      <%= f.label :venue_name, "Venue Name" %><br />
      <%= f.text_field :venue_name %>
    </div>


    <div class="field">
      <%= f.label :street_name, "Street Address" %><br />
      <%= f.text_field :street_name %>
    </div>

    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_field :city %>
    </div>

    <div class="field">
      <%= f.label :state %><br />
      <%= f.text_field :state %>
    </div>

    <div class="field">
      <%= f.label :zip_code, "Zip Code" %><br />
      <%= f.text_field :zip_code %>
    </div>

    <div class="field">
      <%= f.label :price_range, "Price Range" %><br />
      <%= f.text_field :price_range %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>


    <div class="actions">
      <%= f.submit "Add Venue" %>
    </div>
    <% end %>
  </div>
</div>

app/views/venues/show.html.erb
<div class="title-header show-footer">
  <h1><%= @venue.venue_name %></h1>
  <p><%= @venue.description %></p>

  <% if @venue.deletable_by(current_user) %>
  <div class="small-6 columns text-center">
    <%= button_to "Edit Venue", edit_venue_path, class: "button", method: "get", label: "Edit Venue"%>
  </div>
  <div class="small-6 columns text-center">
    <%= button_to "Delete Venue", venue_path, class: "button", method: "delete", label: "Delete Venue"%>
  </div>
  <% end %>

<h3>Reviews</h3>

<table>
  <tbody>
    <%= render @reviews %>
  </tbody>
</table>

<div class="text-center">
  <a href="<%= new_venue_review_path(@venue) %>" class="button">Add a New Review</a>
</div>

<div class="text-center">
  <a href="<%= venues_path %>" class="button">All Venues</a>
</div>

<%= paginate @reviews %>
</div>