config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get '/search' => 'search#index'

  devise_for :users

  as :user do
    get 'users', :to => 'venues#index', :as => :user_root
  end

  resources :users
  resources :venues do
    resources :reviews
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  namespace :api do
    resources :venues do
      resources :reviews, only: [:update]
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer text-center">
    <h4>Follow us:</h4>
    <a href="https://www.twitter.com"><img class="twitter" src="https://lh3.ggpht.com/lSLM0xhCA1RZOwaQcjhlwmsvaIQYaP3c5qbDKCgLALhydrgExnaSKZdGa8S3YtRuVA=w300"></a></li>
  </div>
</footer>

app/views/layouts/_off_canvas_menu.html.erb
<a class="right-off-canvas-toggle" href="#" >
  <div class="menu">
    <div class="off-canvas-bar"></div>
    <div class="off-canvas-middle-bar"></div>
    <div class="off-canvas-bottom-bar"></div>
  </div>
</a>
<!-- Off Canvas Menu -->
<aside class="right-off-canvas-menu">
    <!-- whatever you want goes here -->
    <ul class="side-nav main">
      <li><a href="#">bowling</a></li>
      <li><a href="#">basketball</a></li>
    </ul>
</aside>

app/views/layouts/_top_bar.html.erb
<div data-sticky-container>
  <div class="sticky" data-sticky data-margin-top=0 style="width:100%";>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a class="animated bounceIn" href="/venues" style="font-family: 'Righteous', cursive; font-size: 25px">Jump<u>e</u>r</a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <% if user_signed_in? %>
          <% if current_user.role == "admin" %>
            <ul class="left">
              <div class="small-6 columns text-center">
                <%= button_to "Admin", admin_users_path, class: "button", method: "get", label: "Admin"%>
              </div>
            </ul>
          <% end %>
        <% end %>
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="has-form">
            <div class="row collapse" style="background-color: #ee6f19">
              <%= form_tag("/search", method: "get") do %>
                <div class="large-8 small-9 columns">
                  <%= text_field_tag :query, params[:query], attr: "Find Stuff" %>
                </div>
                <div class="large-4 small-3 columns">
                  <%= submit_tag "Search", name: nil %>
                </div>
              <% end %>
            </div>
          </li>
          <li class="has-dropdown">
            <a href="#">Filter by Boston Neighborhood</a>
            <ul class="dropdown">
              <li><a href="#">Back Bay</a></li>
              <li><a href="#">Central Square</a></li>
            </ul>
          </li>
          <% if user_signed_in? %>
            <% unless current_user.avatar.url.nil? %>
              <li class="picture"><%= image_tag(current_user.avatar) %></li>
            <% end %>
          <li><%= link_to "Profile", "/users/#{current_user.id}" %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li id="sign-in"><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>
  </div>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Jumper" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/top_bar" %>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <%= render "layouts/off_canvas_menu" %>
          <div class="row">
            <%= render "layouts/flash" %>
            <%= yield %>
          </div>
        <%= render "layouts/footer" %>
        <a class="exit-off-canvas"></a>
      </div>
    </div>
  </body>
</html>